CATEGORY_CHOICES = [
        ('Fiction', 'Fiction'),
        ('Non-Fiction', 'Non-Fiction'),
        # ('Science Fiction', 'Science Fiction'),
        ('Mystery', 'Mystery'),
        ('Fantasy', 'Fantasy'),
        ('Romance', 'Romance'),
        ('Horror', 'Horror'),
        ('Thriller', 'Thriller'),
        ('Poetry', 'Poetry'),
        ('Classic', 'Classic'),
        ('Biography', 'Biography'),
        ('Autobiography', 'Autobiography'),
        ('Memoir', 'Memoir'),
        ('History', 'History'),
        ('Travel', 'Travel'),
        ('Cookbook', 'Cookbook'),
        ('Art', 'Art'),
        ('Philosophy', 'Philosophy'),
        ('Religion', 'Religion'),
        ('Science', 'Science'),
        ('Technology', 'Technology'),
        ('Self-Help', 'Self-Help'),
        ('Health', 'Health'),
        ('Education', 'Education'),
        ('Children', 'Children'),
    ]