# Generated by Django 5.0 on 2024-02-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/media/uploads'),
        ),
    ]
